const Submission = require('C:/WUSTL FL 2024/CSE 330/Modules/Module 7/creative-project-cp_528660_528553/330_Final/server/models/submissionModel.jsx');
const Assignment = require('C:/WUSTL FL 2024/CSE 330/Modules/Module 7/creative-project-cp_528660_528553/330_Final/server/models/assignmentModel.jsx');

exports.uploadSubmission = async (req, res) => {
  try {
    const { assignmentId, studentId, studentName, submittedDate } = req.body;

    if (!req.file) {
      return res.status(400).json({ message: "No file uploaded." });
    }

    // Construct the submission document
    const submission = new Submission({
      assignmentId,
      studentId,
      studentName,
      submittedDate,
      fileLink: req.file.path, // File path generated by Multer
      grade: null,
    });

    // Save the submission to the database
    const savedSubmission = await submission.save(); // FIX: Call save on the instance

    // Update the Assignment collection's submissions array
    await Assignment.findByIdAndUpdate(
      assignmentId,
      { $push: { submissions: savedSubmission._id } }, // Add submission ID to submissions array
      { new: true }
    );

    res.status(201).json({
      message: "Submission uploaded successfully.",
      submission: savedSubmission, // Use savedSubmission for consistency
    });
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: "Failed to upload submission." });
  }
};
